spring:
  application:
    name: demo_test
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_test
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: MyVerySecurePassword
    # configuration cache type
    cache:
      type: redis

config:
  security:
    secret: f657b26be28a331aac6b37ef6ca956296ce36a19e51a70af6d25365fb993535f
    expiration: 3600000 # ms
    refresh-token-expiration: 3 # hr
  pagination:
    base-url: http://localhost:8080/api/v1
    url:
      product: /products/paginated
      stock: /stocks/paginated
      supplier: /suppliers/paginated
      user: /users/paginated
      order: /orders/paginated