spring:
  application:
    name: demo_test
  datasource:
    url: jdbc:postgresql://localhost:5432/db_staging
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

config:
  security:
    secret: f657b26be28a331aac6b37ef6ca956296ce36a19e51a70af6d25365fb993535f
    expiration: 100000 # ms